[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    blynkkk/Blynk
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BMP085 Library
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306